# Generated by Django 6.0.3 on 2026-04-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, help_text='Paste an image URL from Unsplash or Google', max_length=1000, null=True),
        ),
    ]
